insertion_2: insertion_2.c check_bpt.c ../syscall_fail.c ../gen_stk.c ../b_plus_tree.c
	gcc -std=c99 -Wall $^ -o $@ -g

BIN_FILES += insertion_2

insertion_1: insertion_1.c print_bpt.c ../syscall_fail.c ../gen_stk.c ../b_plus_tree.c
	gcc -std=c99 -Wall $^ -o $@ -g

BIN_FILES += insertion_1

deletion_1: deletion_1.c  print_bpt.c ../syscall_fail.c ../gen_stk.c ../b_plus_tree.c
	gcc -std=c99 -Wall $^ -o $@ -g

BIN_FILES += deletion_1

deletion_2: deletion_2.c  print_bpt.c check_bpt.c ../syscall_fail.c ../gen_stk.c ../b_plus_tree.c
	gcc -std=c99 -Wall $^ -o $@ -g

BIN_FILES += deletion_2

deletion_3: deletion_3.c  print_bpt.c check_bpt.c ../syscall_fail.c ../gen_stk.c ../b_plus_tree.c
	gcc -std=c99 -Wall $^ -o $@ -g

BIN_FILES += deletion_3

read_d3: read_d3.c
	gcc -std=c99 -Wall $^ -o $@ -g

BIN_FILES += read_d3

deletion_2_1: deletion_2_1.c  print_bpt.c check_bpt.c ../syscall_fail.c ../gen_stk.c ../b_plus_tree.c
	gcc -std=c99 -Wall $^ -o $@ -g

BIN_FILES += deletion_2_1

include ../comm.mk
